### ISSUE TITLE
Can't optimize large models using the CLI 

### ISSUE THREAD

**Issue by agemagician** [huggingface/optimum#901]
### System Info

```shell
Colab using the latest optimum git commit.
```

### Who can help?

@lewtun, @michaelbenayoun

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hello,

CLI works when exporting t5 models, but it fails to optimize it because the model is larger than 2GB.
Here are the steps to reproduce the issue: 
Note that model_name has been masked as it is a private t5 model.

`optimum-cli export onnx --model {model_name} --opset 13 --optimize O3 t5_onnx/`

```
2023-03-18 20:02:20.531794: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-18 20:02:20.531916: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-18 20:02:20.531936: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-18 20:02:25.977836: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-18 20:02:25.977937: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-18 20:02:25.977954: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Framework not specified. Using pt to export to ONNX.
Automatic task detection to seq2seq-lm-with-past.
Using framework PyTorch: 2.0.0+cu117
Overriding 1 configuration item(s)
	- use_cache -> False
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Saving external data to one file...
Using framework PyTorch: 2.0.0+cu117
Overriding 1 configuration item(s)
	- use_cache -> True
/usr/local/lib/python3.9/dist-packages/transformers/modeling_utils.py:796: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if causal_mask.shape[1] < attention_mask.shape[1]:
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Saving external data to one file...
Using framework PyTorch: 2.0.0+cu117
Overriding 1 configuration item(s)
	- use_cache -> True
Asked a sequence length of 16, but a sequence length of 1 will be used with use_past == True for `decoder_input_ids`.
/usr/local/lib/python3.9/dist-packages/transformers/models/t5/modeling_t5.py:507: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif past_key_value.shape[2] != key_value_states.shape[1]:
In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#avoid-inplace-operations-when-using-tensor-shape-in-tracing-mode
In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#avoid-inplace-operations-when-using-tensor-shape-in-tracing-mode
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Saving external data to one file...
/usr/local/lib/python3.9/dist-packages/optimum/onnxruntime/configuration.py:735: FutureWarning: disable_embed_layer_norm will be deprecated soon, use disable_embed_layer_norm_fusion instead, disable_embed_layer_norm_fusion is set to True.
  warnings.warn(
Optimizing model...
symbolic shape inference disabled or failed.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/onnx/__init__.py:72 in _serialize     │
│                                                                              │
│    69 │   │   return proto                                                   │
│    70 │   if hasattr(proto, "SerializeToString") and callable(proto.Serializ │
│    71 │   │   try:                                                           │
│ ❱  72 │   │   │   result = proto.SerializeToString()                         │
│    73 │   │   except ValueError as e:                                        │
│    74 │   │   │   if proto.ByteSize() >= onnx.checker.MAXIMUM_PROTOBUF:      │
│    75 │   │   │   │   raise ValueError(                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 
4608011945

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /usr/lib/python3.9/runpy.py:197 in _run_module_as_main                       │
│                                                                              │
│   194 │   main_globals = sys.modules["__main__"].__dict__                    │
│   195 │   if alter_argv:                                                     │
│   196 │   │   sys.argv[0] = mod_spec.origin                                  │
│ ❱ 197 │   return _run_code(code, main_globals, None,                         │
│   198 │   │   │   │   │    "__main__", mod_spec)                             │
│   199                                                                        │
│   200 def run_module(mod_name, init_globals=None,                            │
│ /usr/lib/python3.9/runpy.py:87 in _run_code                                  │
│                                                                              │
│    84 │   │   │   │   │      __loader__ = loader,                            │
│    85 │   │   │   │   │      __package__ = pkg_name,                         │
│    86 │   │   │   │   │      __spec__ = mod_spec)                            │
│ ❱  87 │   exec(code, run_globals)                                            │
│    88 │   return run_globals                                                 │
│    89                                                                        │
│    90 def _run_module_code(code, init_globals=None,                          │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/optimum/exporters/onnx/__main__.py:25 │
│ 5 in <module>                                                                │
│                                                                              │
│   252                                                                        │
│   253                                                                        │
│   254 if __name__ == "__main__":                                             │
│ ❱ 255 │   main()                                                             │
│   256                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/optimum/exporters/onnx/__main__.py:21 │
│ 2 in main                                                                    │
│                                                                              │
│   209 │   │   optimization_config = AutoOptimizationConfig.with_optimization │
│   210 │   │                                                                  │
│   211 │   │   optimization_config.disable_shape_inference = True             │
│ ❱ 212 │   │   optimizer.optimize(save_dir=args.output, optimization_config=o │
│   213 │                                                                      │
│   214 │   # Optionally post process the obtained ONNX file(s), for example t │
│   215 │   # TODO: treating stable diffusion separately is quite ugly         │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/optimum/onnxruntime/optimization.py:1 │
│ 92 in optimize                                                               │
│                                                                              │
│   189 │   │   │                                                              │
│   190 │   │   │   suffix = f"_{file_suffix}" if file_suffix else ""          │
│   191 │   │   │   output_path = save_dir.joinpath(f"{model_path.stem}{suffix │
│ ❱ 192 │   │   │   optimizer.save_model_to_file(output_path.as_posix(), use_e │
│   193 │   │                                                                  │
│   194 │   │   # Save the model configuration                                 │
│   195 │   │   self.config.save_pretrained(save_dir)                          │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/onnxruntime/transformers/models/gpt2/ │
│ ../../onnx_model.py:998 in save_model_to_file                                │
│                                                                              │
│    995 │   │   #       You need reload the onnx model if you want to read te │
│    996 │   │   #       It is because the base directory is not updated for s │
│    997 │   │   #       might encounter error since external data cannot be l │
│ ❱  998 │   │   OnnxModel.save(self.model, output_path, use_external_data_for │
│    999 │   │   logger.info(f"Model saved to {output_path}")                  │
│   1000 │                                                                     │
│   1001 │   def get_graph_inputs_excluding_initializers(self):                │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/onnxruntime/transformers/models/gpt2/ │
│ ../../onnx_model.py:988 in save                                              │
│                                                                              │
│    985 │   │   │   │   convert_attribute=convert_attribute,                  │
│    986 │   │   │   )                                                         │
│    987 │   │   else:                                                         │
│ ❱  988 │   │   │   save_model(model, output_path)                            │
│    989 │                                                                     │
│    990 │   def save_model_to_file(self, output_path, use_external_data_forma │
│    991 │   │   logger.info("Sort graphs in topological order")               │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/onnx/__init__.py:231 in save_model    │
│                                                                              │
│   228 │   │   basepath = os.path.dirname(model_filepath)                     │
│   229 │   │   proto = write_external_data_tensors(proto, basepath)           │
│   230 │                                                                      │
│ ❱ 231 │   s = _serialize(proto)                                              │
│   232 │   _save_bytes(s, f)                                                  │
│   233                                                                        │
│   234                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/onnx/__init__.py:75 in _serialize     │
│                                                                              │
│    72 │   │   │   result = proto.SerializeToString()                         │
│    73 │   │   except ValueError as e:                                        │
│    74 │   │   │   if proto.ByteSize() >= onnx.checker.MAXIMUM_PROTOBUF:      │
│ ❱  75 │   │   │   │   raise ValueError(                                      │
│    76 │   │   │   │   │   "The proto size is larger than the 2 GB limit. "   │
│    77 │   │   │   │   │   "Please use save_as_external_data to save tensors  │
│    78 │   │   │   │   ) from e                                               │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: The proto size is larger than the 2 GB limit. Please use 
save_as_external_data to save tensors separately from the model file.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│                                                                              │
│ /usr/local/bin/optimum-cli:8 in <module>                                     │
│                                                                              │
│   5 from optimum.commands.optimum_cli import main                            │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(main())                                                     │
│   9                                                                          │
│ /usr/local/lib/python3.9/dist-packages/optimum/commands/optimum_cli.py:40 in │
│ main                                                                         │
│                                                                              │
│   37 │                                                                       │
│   38 │   # Run                                                               │
│   39 │   service = args.func(args)                                           │
│ ❱ 40 │   service.run()                                                       │
│   41                                                                         │
│   42                                                                         │
│   43 if __name__ == "__main__":                                              │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/optimum/commands/export/onnx.py:191   │
│ in run                                                                       │
│                                                                              │
│   188 │                                                                      │
│   189 │   def run(self):                                                     │
│   190 │   │   full_command = f"python3 -m optimum.exporters.onnx {self.args_ │
│ ❱ 191 │   │   subprocess.run(full_command, shell=True, check=True)           │
│   192                                                                        │
│                                                                              │
│ /usr/lib/python3.9/subprocess.py:528 in run                                  │
│                                                                              │
│    525 │   │   │   raise                                                     │
│    526 │   │   retcode = process.poll()                                      │
│    527 │   │   if check and retcode:                                         │
│ ❱  528 │   │   │   raise CalledProcessError(retcode, process.args,           │
│    529 │   │   │   │   │   │   │   │   │    output=stdout, stderr=stderr)    │
│    530 │   return CompletedProcess(process.args, retcode, stdout, stderr)    │
│    531                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command 'python3 -m optimum.exporters.onnx --model {model_name}
--opset 13 --optimize O3 t5_onnx/' returned non-zero exit status 1.
```

The solution from my side is to change "use_external_data_format" default value to True:
```
sed -i -e 's/use_external_data_format: bool = False,/use_external_data_format: bool = True,/g' \
/usr/local/lib/python3.9/dist-packages/optimum/onnxruntime/optimization.py
```

I think this value should be True by default not False by default.

### Expected behavior

The CLI should optimize large models.

**Comment by fxmarty** [comment]
Hi @agemagician , thank you for the report. This should be fixed in https://github.com/huggingface/optimum/pull/886

**Comment by fxmarty** [comment]
Note that the issue is remaining with O4 which uses ORT float16 conversion: https://github.com/microsoft/onnxruntime/issues/15063

**Comment by lxe** [comment]
There doesn't seem to be a command like flag for `use_external_data_format: bool = True,` when using `optimum-cli onnxruntime quantize`, so I had to manually change it in `quantization.py: quantize()` function.

**Comment by fxmarty** [comment]
Thank you, this should hopefully be fixed in the upcoming release: https://github.com/huggingface/optimum/pull/886

**Comment by puyuanOT** [comment]
Hi guys, I still have this error when running optimum-cli export onnx --model EleutherAI/pythia-2.8b /local_disk0/optimized_pythia_2.8b_fp16 --optimize O4 --task text-generation-with-past --framework pt --device cuda

**Comment by regisss** [comment]
@puyuanOT I think we need to wait for the next release of ONNXRuntime which will have a fix for fp16 conversion issues: https://github.com/microsoft/onnxruntime/pull/15067

**Comment by puyuanOT** [comment]
> @puyuanOT I think we need to wait for the next release of ONNXRuntime which will have a fix for fp16 conversion issues: [microsoft/onnxruntime#15067](https://github.com/microsoft/onnxruntime/pull/15067)

I believe the new ONNXRuntime is now published.

**Comment by fxmarty** [comment]
@puyuanOT Due to this check https://github.com/microsoft/onnxruntime/blob/ba5f5e319807126eb35ced2cfabd56a7e358ad15/onnxruntime/python/tools/transformers/float16.py#L204, we'll need to change the optimize method to write large models to disk first before calling `convert_float_to_float16`.

**Comment by drxmy** [comment]
> @puyuanOT Due to this check https://github.com/microsoft/onnxruntime/blob/ba5f5e319807126eb35ced2cfabd56a7e358ad15/onnxruntime/python/tools/transformers/float16.py#L204, we'll need to change the optimize method to write large models to disk first before calling `convert_float_to_float16`.

Looking forward to your pr(https://github.com/huggingface/optimum/pull/1079 ). I tried onnxruntime 1.15. With fp16 convert, it gave similiar failure.
